export default {
    cs: {
        /** navigation */
        nav_items: "Produkty",
        nav_manufacturers: "Výrobci, prodejci",
        nav_users: "Uživatelé",

        /** basic */
        login_title: "Přihlášení",
        email: "E-mail",
        password: "Heslo",
        required: "Toto pole je povinné",
        not_valid_mail: "Toto není platný e-mail",
        forgotten_password: "Zapomenuté heslo",
        login: "Přihlásit",
        invalid_login: "Neexistující email nebo špatné heslo",
        created_at: "Vytvořeno",
        deleted_at: "Smazáno",
        updated_at: "Upraveno",
        error: "Nastala chyba",
        search: "Vyhledat",
        yes_arg: "Ano",
        no_arg: "Ne",
        save_arg: "Uložit",
        form_invalid: "Zkontrolujte všechna data",
        close_arg: "Zavřít",
        per_page: "Záznamů na stránku",
        no_data: "Žádné dostupné výsledky",
        no_matching: "Nebyly nalezeny žádné shody",
        description: "Popis",
        saved: "Uloženo",
        date_created_at: "Datum vytvoření",
        date_updated_at: "Poslední úprava",
        delete: "Smazat",
        confirm_delete: "Opravdu si přejete dokončit operaci ?",
        deleted: "Smazáno",
        renew: "Obnovit",
        renewed: "Obnoveno",
        name: "Jméno",
        change_media: "Změnit médium",
        image: "Obrázek",
        pass: "Heslo",
        pass_again: "Heslo znovu",
        pass_not_same: "Hesla se neshodují",
        edit: "Upravit",
        show: "Zobrazit",
        add_basic: "Přidat",
        back: "Zpět",
        company_name: "Název společnosti",
        delivery_time: "Doba doručení",
        note: "Poznámka",
        home: "Domů",
        customer_search: "Vyhledat zákazníka",
        customer_not_found: "Zákazník nebyl nalezen",
        item_name_missing: "Jméno produktu musí být vyplněno pro každý jazyk",
        /** users */
        users: "Uživatelé",
        first_name: "Jméno",
        last_name: "Přijmení",
        full_name: "Celé jméno",
        user_detail: "Detail uživatele",
        user_state: "Stát",
        user_city: "Město",
        user_street: "Ulice",
        user_no: "Číslo domu",
        user_zip: "PSČ",
        user_phone_number: "Telefonní číslo",
        user_vat: "DIČ",
        user_cin: "IČO",
        user_orders: "Počet objednávek",
        user_orders_today: "Z toho dnes",
        user_count: "Počet uživatelů",
        user_count_today: "z toho dnes registrovaných",

        order_detail: "Detail objednávky",
        order_id: "ID objednávky",
        order_number: "číslo objednávky",
        order_items_count: "počet kusů",
        order_items_price: "cena celkem",
        order_payment: "platba",
        /** items */
        items_title: "Produkty",
        product_name: "Produkt",
        product_unit: "Jednotka",
        product_price: "Cena",
        product_variants: "Varianty",
        new_product: "Nový produkt",
        name_product: "Název",
        unit_price_product: "Jednotková cena",
        product_description: "Popis produktu",
        product_description_short: "Krátký popis",
        check_sku: "Zkontrolovat SKU",
        check_ean: "Zkontrolovat EAN kód",
        media_gallery: "Galerie médií",
        item_variants: "Varianty produktu",
        add_item_variant: "Přidat variantu",
        add_media_to_item: "Přidat médium",
        item_variant_attributes_title: "Attributy produktu",
        item_variant_meta_type_placeholder: "Typ (Barva, Velikost ...)",
        item_variant_meta_value_placeholder: "Hodnota typu (Modrá, S, M ...)",
        add_variant_attribute: "Přidat attribut",
        item_variant_media_title: "Galerie varianty",
        add_variant_media: "Přidat médium",
        item_detail: "Detail produktu",
        item_similars: "Podobné produkty",
        item_in_sale: "V prodeji",
        item_sale: "Sleva",
        item_sale_price: "Cena ve slevě",
        item_use_stock: "Používat sklad",
        item_stock_quantity: "Na skladě",
        item_bestseller: "Bestseller",
        item_recommended: "Doporučeno",
        item_news: "Novinka",
        item_stock_download_file: "Stáhnout xls strukturu pro import",
        items_count: "Počet produktů",
        bestsellers: "Nejprodávanější produkty",
        last_orders: "Poslední objednávky",

        order_single_title: "Objednávka",
        /** manufacturers */
        manufacturers_title: "Výrobci, dodavatelé",
        new_manufacturer: "Nový výrobce",
        manufacturers_name: "Jméno",
        manufacturer_description: "Popis výrobce",
        manufacturer_detail: "Detail výrobce",
        manufacturer_title: "Výrobce",

        /** categories */
        categories_title: "Kategorie",
        categories_new: "Nová kategorie",
        categories_description: "Popis kategorie",

        /** groups */
        groups_title: "Skupiny",
        groups_new: "Nová skupina",
        groups_single: "Skupina",

        /** stock */
        stock_title: "Sklad",
        stock_quantity: "Počet",
        stock_set_quantity: "Zadejte počet",

        /**orders */
        orders_title: "Objednávky",
        orders_id: "Interní id",
        orders_shipped: "Expedováno",
        orders_total_price: "Celková cena",
        order_status: "Stav",
        order_payment_method: "Platební metoda",
        orders_count: "Počet ks",
        orders_delivery: "Doprava",
        new_order: "Vytvořit objednávku",
        change_delivery_addresss: "Změnit doručovací údaje",
        change_invoice_address: "Změnit fakturační údaje",
        // statuses
        order_created: "Vytvořeno",
        order_paid: "Zaplaceno",
        order_refunded: "Vráceno",
        order_canceled: "Zrušeno",
        order_timeouted: "Platba vypršela",
        order_shipped: "Expedováno",
        // payment methods
        order_pm_checks: "Dobírka",
        order_pm_bank_transfer: "Převodem",
        order_invoice_info: "Fakturační údaje",
        order_change_status: "Změna stavu",
        // delivery types
        order_dt_personal: "Osobní odběr",
        order_dt_logistic: "Logistika",

        order_customer: "zákazník",

        // order status helpers
        order_created_text: "objednávka byla vytvořena",
        order_paid_text: "objednávka byla zaplacena",
        order_canceled_text: "objednávka byla zrušena",
        order_refunded_text: "plaba vrácena na účet zákazníka",
        order_timeouted_text: "platba vypršela",
        order_shipped_text: "objednávaka byla expedována",

        // blog
        blog_new: "Nový příspěvek",
        blog_published: "Publikováno",
        blog_favourite: "Hlavní",
        blog_content: "Obsah",
        blog_keyword: "Klíčová slova",
        blog_description: "Popis",

        blog_categories: "Blog kategorie",
        // cms
        cms_title: "Podstránky",
        cms_new_page: "Nová podstránka",
        cms_page_title: "Název stránky",
        cms_page_heading: "Nadpis",
        cms_foreign_lang: "Druhý jazyk",

        // parameters
        parameters_title: "Parametry",
        parameters_new: "Nový parameter",
        parameters_add_type: "Nová hodnota",
        parameters_type: "Typ",

        // types
        types_title: "Platební metody / Doprava",
        types_payment_title: "Platební metody",
        type_delivery_title: "Doprava",
        type_new_type: "Nový typ",

        vat_rate: "Sazba daně",

        new_delivery: "Nový typ dopravy",
        new_payment: "Nový typ platby",

        total_spent: "Celková útrata",
        delivery_addresses: "Doručovací údaje",
        invoice_addresses: "Fakturační údaje",
        user_full_address: "Adresa",
        invoice_title: "Faktura",
        add_to_order: "Přidat do objednávky",
        remove_order: "Smazat objednávku",
        change_address: "Změna údajů",

        today_stats: "z toho dnes",
        customer_th: "zákazník",
        color: "Barva",
        add_to_order_helper_text:
            "<div class='my-3'>Pro přidání produktu: <ul class='mt-1'><li class='small'>Vyberte produkt</li><li class='small'>Zadejte počet</li><li class='small'>Klikněte na tlačítko <b>&quot;Přidat&quot;</b></li></ul></div>",
        add_track_url: "Přidat trackovací url",
        units: "Jednotky",
        unit_title: "Jednotka",
        price_for: "Cena za",
        item_free_shipping: "Doprava zdarma",
        tags_title: "Značky - Štítky",
        new_tag: "Nová značka",
        parent_category: "Nadřazená kategorie",
        child_category: "Podkategorie",
        avatar_image: "Náhledový obrázek"
    },
    en: {
        /** basic */
        login_title: "Login",
        email: "E-mail",
        password: "Password",
        required: "This field is required",
        not_valid_mail: "This is not valid e-mail",
        forgotten_password: "Forgotten password",
        login: "Login",
        invalid_login: "Invalid user credentials",
        created_at: "Created at",
        deleted_at: "Deleted at",
        updated_at: "Updated at",
        error: "An error occured",
        search: "Search",
        yes_arg: "Yes",
        no_arg: "No",
        save_arg: "Save",
        form_invalid: "Check all inputs",
        close_arg: "Close",
        no_data: "No data available",
        no_matching: "No matching records found",
        per_page: "Items per page",
        description: "Description",
        saved: "Saved",
        date_created_at: "Created at",
        date_updated_at: "Last updated at",
        delete: "Delete",
        confirm_delete: "Are you sure ?",
        deleted: "Deleted",
        name: "Name",
        change_media: "Change media",
        image: "Image",
        pass: "Password",
        pass_again: "Password again",
        pass_not_same: "Passwords are not same",
        edit: "Edit",
        show: "Show",
        add_basic: "Add",
        company_name: "Company name",
        delivery_time: "Delivery time",
        note: "Note",
        home: "Home",
        customer_search: "Search customer",
        customer_not_found: "Customer was not found",
        item_name_missing: "Item name is required for each language",
        /** users */
        users: "Users",
        first_name: "First name",
        last_name: "Last name",
        full_name: "Full name",
        user_detail: "User detail",
        user_state: "State",
        user_city: "City",
        user_street: "Street",
        user_no: "House no",
        user_zip: "ZIP",
        user_phone_number: "Phone number",
        user_vat: "TIN",
        user_cin: "CIN",
        user_orders: "Orders count",
        /** items */
        items_title: "Items",
        product_name: "Product name",
        product_unit: "Unit",
        product_price: "Price",
        product_variants: "Variants",
        new_product: "New product",
        name_product: "Name",
        unit_price_product: "Unit price",
        product_description: "Product description",
        product_description_short: "Short description",
        check_sku: "Check SKU",
        check_ean: "Check EAN",
        media_gallery: "Media gallery",
        add_media_to_item: "Add media",
        add_item_variant: "Add item variant",
        item_variants: "Item variants",
        item_variant_attributes_title: "Item attributes",
        item_variant_meta_type_placeholder: "Type (Color, size ...)",
        item_variant_meta_value_placeholder: "Value of type (Blue, S, M ...)",
        add_variant_attribute: "Add item attribute",
        item_detail: "Product detail",
        item_variant_media_title: "Variant gallery",
        add_variant_media: "Add varriant media",
        item_similars: "Similar items",
        item_in_sale: "For sale",
        item_sale: "Sale",
        item_sale_price: "Sale price",
        item_use_stock: "Use stock",
        item_stock_quantity: "Stock quantity",
        item_bestseller: "Bestseller",
        item_recommended: "Recommended",
        item_news: "News",
        item_stock_download_file: "Download structure",
        items_count: "Items count",
        /** manufacturers */
        manufacturers_title: "Manufacturers",
        new_manufacturer: "New manufacturer",
        manufacturer_description: "Manufacturer desctiption",
        manufacturer_detail: "Manufacturer detail",

        /** categories */
        categories_title: "Categories",
        categories_new: "New category",
        categories_description: "Category description",

        /** groups */
        groups_title: "Groups",
        groups_new: "New group",
        groups_single: "Group",

        /** stock */
        stock_title: "Stock",
        stock_quantity: "Quantity",
        stock_set_quantity: "Set quantity",

        /**orders */
        orders_title: "Orders",
        orders_id: "Internal id",
        orders_shipped: "Shipped",
        orders_total_price: "Total price",
        order_status: "Status",
        order_payment_method: "Payment method",
        orders_count: "Count",
        orders_delivery: "Delivery",
        new_order: "Create order",
        change_delivery_addresss: "Change delivery address",
        change_invoice_address: "Change invoice address",
        // statuses
        order_created: "Created",
        order_paid: "Paid",
        order_refunded: "Refunded",
        order_canceled: "Canceled",
        order_timeouted: "Timeouted",
        // payment methods
        order_pm_checks: "Checks",
        order_pm_bank_transfer: "Bank transfer",
        order_invoice_info: "Invoice info",
        order_change_status: "Change state",
        // delivery types
        order_dt_personal: "Personal",
        order_dt_logistic: "Logistic",
        //blog
        blog_new: "New post",
        blog_published: "Published",
        blog_favourite: "Favourite",
        blog_content: "Content",
        blog_keyword: "Keywords",
        blog_description: "Description",

        blog_categories: "Blog categories",
        // cms
        cms_title: "Subpages",
        cms_new_page: "New subpage",
        cms_page_title: "Page name",
        cms_page_heading: "Heading",
        cms_foreign_lang: "Foreign language",

        // parameters
        parameters_title: "Parameters",
        parameters_add_type: "Add type",

        // types
        types_title: "Payment methods / Delivery",
        types_payment_title: "Payment types",
        type_delivery_title: "Delivery types",
        type_new_type: "New type",
        vat_rate: "VAT rate",

        new_delivery: "New delivery type",
        new_payment: "New payment type",
        total_spent: "Spent",

        delivery_addresses: "Delivery addresses",
        invoice_addresses: "Invoice addresses",
        user_full_address: "Address",
        invoice_title: "Invoice",
        add_to_order: "Add to order",
        remove_order: "Remove order",
        change_address: "Change address",
        tags_title: "Tags"
    }
};
